var actions = [
	{ name: "True Thrust",
	  shortName: "TT",
	  id: 0,
	  description: "Delivers an attack with a potency of 160.",
	  potency: 150,
	  type: "Weaponskill",
	  group: "combo1"},
	{ name: "Vorpal Thrust",
	  shortName: "VT",
	  id: 1,
	  description: "Delivers an attack with a potency of 100.<br/>Combo Action: True Thrust<br/>Combo Potency: 250",
	  potency: 260,
	  type: "Weaponskill",
	  group: "combo1"},
	{ name: "Full Thrust",
	  shortName: "FT",
	  id: 2,
	  description: "Delivers an attack with a potency of 100.<br/>Combo Action: Vorpal Thrust<br/>Combo Potency: 450<br/>Blood of the Dragon Combo Bonus: Grants Sharper Fang and Claw<br/>Duration: 10s",
	  potency: 450,
	  effects: ["Sharper Fang and Claw"],
	  type: "Weaponskill",
	  group: "combo1"},
	{ name: "Fang and Claw",
	  shortName: "FC",
	  id: 3,
	  description: "Delivers an attack with a potency of 260.<br/>300 when executed from a target's flank.<br/>Can only be executed while under the effect of both Blood of the Dragon and Sharper Fang and Claw.<br/>Additional Effect: Extends Blood of the Dragon duration by 10s to a maximum of 30s",
	  potency: 300,
	  effects: ["Enhanced Wheeling Thrust"],
	  type: "Weaponskill",
	  group: "combo1"},

	{ name: "Impulse Drive",
	  shortName: "ID",
	  id: 4,
	  description: "Delivers an attack with a potency of 200.",
	  potency: 200,
	  type: "Weaponskill",
	  group: "combo2"},
	{ name: "Disembowel",
	  shortName: "DE",
	  id: 5,
	  description: "Delivers an attack with a potency of 100.<br/>Combo Action: Impulse Drive<br/>Combo Potency: 240<br/>Combo Bonus: Reduces target's piercing resistance by 5%<br/>Duration: 30s",
	  potency: 240,
	  effects: ["Piercing Resistance Down"],
	  type: "Weaponskill",
	  group: "combo2"},
	{ name: "Chaos Thrust",
	  shortName: "CT",
	  id: 6,
	  description: "Delivers an attack with a potency of 100.<br/>140 when executed from a target's rear.<br/>Combo Action: Disembowel<br/>Combo Potency: 240<br/>Rear Combo Potency: 280<br/>Combo Bonus: Damage over time<br/>Potency: 35<br/>Duration: 30s<br/>Blood of the Dragon Combo Bonus: Grants Enhanced Wheeling Thrust<br/>Duration: 10s",
	  potency: 280,
	  effects: ["Chaos Thrust", "Enhanced Wheeling Thrust"],
	  type: "Weaponskill",
	  group: "combo2"},
	{ name: "Wheeling Thrust",
	  shortName: "WT",
	  id: 7,
	  description: "Delivers an attack with a potency of 260.<br/>300 when executed from a target's rear.<br/>Can only be executed while under the effect of both Blood of the Dragon and Enhanced Wheeling Thrust.<br/>Additional Effect: Extends Blood of the Dragon duration by 10s to a maximum of 30s",
	  potency: 300,
	  effects: ["Sharper Fang and Claw"],
	  type: "Weaponskill",
	  group: "combo2"},

	{ name: "Heavy Thrust",
	  shortName: "HT",
	  id: 8,
	  description: "Delivers an attack with a potency of 150.<br/>190 when executed from a target's flank.<br/>Additional Effect: Increases damage dealt by 10%<br/>Duration: 30s",
	  potency: 190,
	  effects: ["Heavy Thrust"],
	  type: "Weaponskill",
	  group: "miscgcd"},
	{ name: "Piercing Talon",
	  shortName: "PT",
	  id: 9,
	  description: "Delivers a ranged attack with a potency of 120.",
	  potency: 120,
	  type: "Weaponskill",
	  group: "miscgcd"},
	{ name: "Doom Spike",
	  shortName: "DS",
	  id: 10,
	  description: "Delivers an attack with a potency of 140 to all enemies in a straight line before you.",
	  potency: 140,
	  type: "Weaponskill",
	  group: "miscgcd"},
	{ name: "Sonic Thrust",
	  shortName: "ST",
	  id: 11,
	  description: "Delivers an attack with a potency of 100 to all enemies in a straight line before you.<br/>Combo Action: Doom Spike<br/>Combo Potency: 180<br/>Combo Bonus: Increases Blood of the Dragon duration by 10s to a maximum of 30s",
	  potency: 180,
	  type: "Weaponskill",
	  group: "miscgcd"},

	{ name: "Blood for Blood",
	  shortName: "BfB",
	  id: 12,
	  description: "Increases damage dealt by 15% and damage suffered by 10%.<br/>Duration: 20s",
	  recast: 80,
	  delayed: "true",
	  effects: ["Blood for Blood"],
	  type: "Ability",
	  group: "buff"},
	{ name: "Dragon Sight",
	  shortName: "DS",
	  id: 13,
	  description: "Grants Right Eye to self and Left Eye to target party member, increasing your damage dealt by 10% and the target party member's damage dealt by 5%, as long as target remains within 12 yalms.<br/>Duration: 20s",
	  recast: 120,
	  delayed: "true",
	  effects: ["Right Eye"],
	  type: "Ability",
	  group: "buff"},
	{ name: "Battle Litany",
	  shortName: "BL",
	  id: 14,
	  description: "Increases critical hit rate of self and nearby party members by 15%.<br/>Duration: 20s",
	  recast: 180,
	  delayed: "true",
	  effects: ["Battle Litany"],
	  type: "Ability",
	  group: "buff"},
	{ name: "Life Surge",
	  shortName: "LS",
	  id: 15,
	  description: "Ensures critical damage for first weaponskill used while Life Surge is active. Damage dealt will be absorbed as HP, up to 10% of maximum HP.<br/>Duration: 10s",
	  recast: 50,
	  effects: ["Life Surge"],
	  type: "Ability",
	  group: "buff"},
	{ name: "Blood of the Dragon",
	  shortName: "BotD",
	  id: 16,
	  description: "Increases potency of Jump and Spineshatter Dive by 30%.<br/>Duration: 20s<br/>Additional Effect: Grants Sharper Fang and Claw upon successfully executing Full Thrust, or Enhanced Wheeling Thrust upon successfully executing Chaos Thrust<br/>Duration: 10s<br/>Effects end upon reuse or upon using a weaponskill other than Fang and Claw or Wheeling Thrust.<br/>Cannot be executed while under the effect of Life of the Dragon.",
	  recast: 30,
	  delayed: "true",
	  effects: ["Blood of the Dragon"],
	  type: "Ability",
	  group: "buff"},
	{ name: "Potion",
	  shortName: "Pot",
	  id: 17,
	  description: "This diluted brew temporarily increases strength, but for twice the duration of similar potions.<br/>Item Level 350<br/>Consumable Bonuses (Duration: 30s) (Recast: 5m / HQ 4m30s)<br/>Strength +8% (Cap: 180) HQ +10% / Cap: 225",
	  recast: 270,
	  animLock: 1.3,
	  delayed: "true",
	  effects: ["Medicated"],
	  type: "Ability",
	  group: "buff"},

	{ name: "Jump",
	  shortName: "Jump",
	  id: 18,
	  description: "Delivers a jumping attack with a potency of 260. Returns you to your original position after the attack is made.<br/>Additional Effect: Grants Dive Ready<br/>Duration: 15s<br/>Cannot be executed while bound.",
	  potency: 260,
	  recast: 30,
	  animLock: 1.3,
	  effects: ["Dive Ready"],
	  type: "Ability",
	  group: "ogcd"},
	{ name: "Spineshatter Dive",
	  shortName: "SSD",
	  id: 19,
	  description: "Delivers a jumping attack with a potency of 210.<br/>Additional Effect: Stun<br/>Duration: 2s<br/>Additional Effect: Grants Dive Ready<br/>Duration: 15s<br/>Cannot be executed while bound.",
	  potency: 210,
	  recast: 60,
	  animLock: 1.3,
	  effects: ["Dive Ready"],
	  type: "Ability",
	  group: "ogcd"},
	{ name: "Dragonfire Dive",
	  shortName: "DFD",
	  id: 20,
	  description: "Delivers a jumping fire-based attack with a potency of 320 to all nearby enemies. Cannot be executed while bound.",
	  potency: 320,
	  recast: 120,
	  animLock: 1.3,
	  type: "Ability",
	  group: "ogcd"},
	{ name: "Mirage Dive",
	  shortName: "MD",
	  id: 21,
	  description: "Delivers an attack with a potency of 210.<br/>Additional Effect: Strengthens the gaze of your Dragon Gauge by 1 while under the effect of Blood of the Dragon or Life of the Dragon<br/>Can only be executed when Dive Ready.",
	  potency: 210,
	  recast: 1,
	  type: "Ability",
	  group: "ogcd"},
	{ name: "Geirskogul",
	  shortName: "GK",
	  id: 22,
	  description: "Delivers an attack with a potency of 230 to all enemies in a straight line before you.<br/>Can only be executed while under the effect of Blood of the Dragon.<br/>Additional Effect: Changes Blood of the Dragon to Life of the Dragon<br/>Dragon Gauge Cost: 3",
	  potency: 230,
	  recast: 30,
	  type: "Ability",
	  group: "ogcd"},
	{ name: "Nastrond",
	  shortName: "NS",
	  id: 23,
	  description: "Delivers an attack with a potency of 330 to all enemies in a straight line before you.<br/>Can only be executed while under the effect of Life of the Dragon.",
	  potency: 330,
	  recast: 10,
	  type: "Ability",
	  group: "ogcd"},
	{ name: "Elusive Jump",
	  shortName: "EJ",
	  id: 24,
	  description: "Executes a jump to a location 15 yalms behind you, while removing any Heavy or Bind effects.<br/>Additional Effect: Reduces enmity by half",
	  recast: 30,
	  animLock: 1.3,
	  type: "Ability",
	  group: "ogcd"},

	{ name: "Second Wind",
	  shortName: "SW",
	  id: 25,
	  description: "Instantly restores own HP.<br/>Cure Potency: 500<br/>Cure potency varies with current attack power.",
	  potency: 500,
	  recast: 120,
	  type: "Ability",
	  group: "crossrole"},
	{ name: "Arm's Length",
	  shortName: "AL",
	  id: 26,
	  description: "Creates a barrier nullifying most knockback and draw-in effects.<br/>Duration: 5s<br/>Additional Effect: Slow +20% when barrier is struck<br/>Duration: 15s",
	  recast: 60,
	  effects: ["Arm's Length"],
	  type: "Ability",
	  group: "crossrole"},
	{ name: "Leg Sweep",
	  shortName: "LS",
	  id: 27,
	  description: "Stuns target.<br/>Duration: 3s",
	  recast: 40,
	  type: "Ability",
	  group: "crossrole"},
	{ name: "Diversion",
	  shortName: "Div",
	  id: 28,
	  description: "Reduces enmity generation.<br/>Duration: 30s",
	  recast: 120,
	  delayed: "true",
	  effects: ["Diversion"],
	  type: "Ability",
	  group: "crossrole"},
	{ name: "Invigorate",
	  shortName: "Inv",
	  id: 29,
	  description: "Instantly restores 400 TP.",
	  potency: 400,
	  recast: 120,
	  type: "Ability",
	  group: "crossrole"},
	{ name: "Bloodbath",
	  shortName: "BB",
	  id: 30,
	  description: "Converts a portion of physical damage dealt into HP.<br/>Duration: 20s",
	  recast: 90,
	  delayed: "true",
	  effects: ["Bloodbath"],
	  type: "Ability",
	  group: "crossrole"},
	{ name: "Goad",
	  shortName: "Goad",
	  id: 31,
	  description: "Refreshes TP of a single party member.<br/>Duration: 30s",
	  potency: 30,
	  effectDuration: 30,
	  recast: 180,
	  type: "Ability",
	  group: "crossrole"},
	{ name: "Feint",
	  shortName: "Feint",
	  id: 32,
	  description: "Lowers target's strength and dexterity by 10%.<br/>Duration: 10s",
	  recast: 120,
	  effects: ["Feint"],
	  type: "Ability",
	  group: "crossrole"},
	{ name: "Crutch",
	  shortName: "Crutch",
	  id: 33,
	  description: "Removes Bind and Heavy from target party member other than self.",
	  potency: 150,
	  recast: 90,
	  type: "Ability",
	  group: "crossrole"},
	{ name: "True North",
	  shortName: "TN",
	  id: 34,
	  description: "Nullifies all action direction requirements.<br/>Duration: 15s",
	  recast: 150,
	  delayed: "true",
	  effects: ["True North"],
	  type: "Ability",
	  group: "crossrole"}

	// { name: "Delay",
	//   shortName: "Delay",
	//   description: "Will be turned into a downtime manager later",
	//   animLock: 1.05,
	//   type: "Ability",
	//   group: "other"}
];

var effects = [
	{ name: "Heavy Thrust",
	  shortName: "HT",
	  description: "Damage dealt is increased.",
	  value: 1.1,
	  duration: 30,
	  activationTime: 1.1,
      stackable: false,
      backgroundColor: "rgb(240, 208, 144)",
      borderColor: "rgb(208, 176, 144)",
      displaySelf: true,
	  type: "Damage"},
	{ name: "Piercing Resistance Down",
	  shortName: "DE",
	  description: "Piercing resistance is reduced.",
	  value: 1.05,
	  duration: 30,
	  activationTime: 1.6,
	  usePattern: [27],
      openerTime: 6.5,
      stackable: false,
      backgroundColor: "rgb(160, 32, 32)",
      borderColor: "rgb(160, 160, 160)",
      displaySelf: true,
      groupAction: "Disembowel",
      job: "drg",
	  type: "Piercing"},
	{ name: "Chaos Thrust",
	  shortName: "CT",
	  description: "Wounds are bleeding, causing damage over time.",
	  value: 35,
	  duration: 30,
	  activationTime: 1.6,
      stackable: false,
      backgroundColor: "rgb(154, 126, 165)",
      borderColor: "rgb(77, 63, 83)",
      displaySelf: true,
	  type: "DoT"},
	{ name: "Blood for Blood",
	  shortName: "BfB",
	  description: "Increasing damage dealt while increasing damage taken.",
	  value: 1.15,
	  duration: 20,
	  activationTime: 0.6,
      stackable: false,
      backgroundColor: "rgb(144, 16, 16)",
      borderColor: "rgb(16, 16, 16)",
      displaySelf: true,
	  type: "Damage"},
	{ name: "Right Eye",
	  shortName: "DS",
	  description: "Damage dealt is increased.",
	  value: 1.1,
	  duration: 20,
	  activationTime: 0.6,
      stackable: false,
      backgroundColor: "rgb(183, 67, 44)",
      borderColor: "rgb(91, 34, 22)",
      displaySelf: true,
	  type: "Damage"},
	{ name: "Battle Litany",
	  shortName: "BL",
	  description: "Critical hit rate is increased.",
	  value: 0.15,
	  duration: 20,
	  activationTime: 0.6,
	  recast: 180,
      openerTime: 4,
      stackable: false,
      backgroundColor: "rgb(208, 240, 240)",
      borderColor: "rgb(71, 206, 206)",
      displaySelf: true,
      groupAction: "Battle Litany",
      job: "drg",
	  type: "Crit"},
	{ name: "Medicated",
	  shortName: "Pot",
	  description: "Performance is being enhanced by a medicinal item.",
	  value: 225,
	  duration: 30,
	  activationTime: 0.93,
      stackable: false,
      backgroundColor: "rgb(48, 80, 144)",
      borderColor: "rgb(80, 48, 16)",
      displaySelf: true,
	  type: "Special"},
	  
	{ name: "Life Surge",
	  shortName: "LS",
	  description: "Next weaponskill will result in a critical hit with resulting damage being absorbed as HP.",
	  duration: 10,
      stackable: false,
      backgroundColor: "rgb(176, 48, 16)",
      borderColor: "rgb(144, 16, 16)",
      displaySelf: true,
	  type: "Special"},
	{ name: "Dive Ready",
	  shortName: "DR",
	  description: "Able to execute Mirage Dive.",
	  duration: 15,
      stackable: false,
      backgroundColor: "rgb(108, 138, 191)",
      borderColor: "rgb(54, 69, 95)",
      displaySelf: true,
	  type: "Special"},
	{ name: "Sharper Fang and Claw",
	  shortName: "SFC",
	  description: "Able to execute Fang and Claw.",
	  value: 0,
	  duration: 10,
      stackable: false,
      backgroundColor: "rgb(208, 240, 240)",
      borderColor: "rgb(112, 48, 16)",
      displaySelf: true,
	  type: "Special"},
	{ name: "Enhanced Wheeling Thrust",
	  shortName: "EWT",
	  description: "Able to execute Wheeling Thrust.",
	  value: 0,
	  duration: 10,
      stackable: false,
      backgroundColor: "rgb(144, 80, 48)",
      borderColor: "rgb(16, 16, 16)",
      displaySelf: true,
	  type: "Special"},
	{ name: "Blood of the Dragon",
	  shortName: "BotD",
	  description: "Potency of Jump and Spineshatter Dive are increased.",
	  value: 1.3,
	  duration: 20,
	  eyes: 0,
	  life: false,
      stackable: false,
      backgroundColor: "rgb(55, 145, 227)",
      eyeColor: "rgb(15, 33, 52)",
      lifeColor: "rgb(255, 60, 60)",
      displaySelf: false,
	  type: "Special"},

	{ name: "Arm's Length",
	  shortName: "AL",
	  description: "Slowing enemies when attacked. Immune to most knockback and draw-in effects.",
	  duration: 5,
	  activationTime: 0.6,
      stackable: false,
      backgroundColor: "rgb(16, 16, 48)",
      borderColor: "rgb(8, 8, 24)",
      displaySelf: true,
	  type: "Special"},
	{ name: "Diversion",
	  shortName: "Div",
	  description: "Enmity generation is reduced.",
	  duration: 30,
	  activationTime: 0.6,
      stackable: false,
      backgroundColor: "rgb(104, 167, 147)",
      borderColor: "rgb(52, 83, 74)",
      displaySelf: true,
	  type: "Special"},
	{ name: "Bloodbath",
	  shortName: "BB",
	  description: "Physical attacks generate HP equal to a portion of damage dealt.",
	  duration: 20,
	  activationTime: 0.6,
      stackable: false,
      backgroundColor: "rgb(80, 16, 16)",
      borderColor: "rgb(48, 16, 16)",
      displaySelf: true,
	  type: "Special"},
	{ name: "Feint",
	  shortName: "Feint",
	  description: "Strength and dexterity are reduced.",
	  duration: 10,
	  activationTime: 0.6,
      stackable: false,
      backgroundColor: "rgb(137, 87, 83)",
      borderColor: "rgb(69, 44, 42)",
      displaySelf: true,
	  type: "Special"},
	{ name: "True North",
	  shortName: "TN",
	  description: "All action direction requirements are nullified.",
	  duration: 15,
	  activationTime: 0.6,
      stackable: false,
      backgroundColor: "rgb(208, 144, 80)",
      borderColor: "rgb(104, 72, 40)",
      displaySelf: true,
	  type: "Special"},

	{ name: "Trick Attack",
	  shortName: "TA",
	  description: "Damage taken is increased.",
	  value: 1.1,
	  duration: 10,
	  recast: 60,
      openerTime: 11,
      stackable: false,
      backgroundColor: "rgb(209, 127 , 15)",
      borderColor: "rgb(31, 31 , 31)",
      displaySelf: false,
      groupAction: "Trick Attack",
      job: "nin",
	  type: "Damage"},
	{ name: "Hypercharge",
	  shortName: "HC",
	  description: "Damage taken is increased.",
	  value: 1.05,
	  duration: 28,
	  recast: 120,
      openerTime: 2,
      stackable: false,
      backgroundColor: "rgb(209, 127 , 15)",
      borderColor: "rgb(31, 31 , 31)",
      displaySelf: false,
      groupAction: "Hypercharge",
      job: "mch",
	  type: "Damage"},
	{ name: "Fey Wind",
	  shortName: "FW",
	  description: "Weaponskill cast time and recast time, spell cast time and recast time, and auto-attack delay are reduced.",
	  value: 3,
	  duration: 30,
	  recast: 60,
      openerTime: -5,
      stackable: false,
      backgroundColor: "rgb(102, 152 , 133)",
      borderColor: "rgb(51, 76 , 67)",
      displaySelf: false,
      groupAction: "Fey Wind",
      job: "sch",
	  type: "Speed"},
	{ name: "Chain Stratagem",
	  shortName: "CS",
	  description: "Rate at which critical hits are taken is increased.",
	  value: 0.15,
	  duration: 15,
	  recast: 120,
      openerTime: 6,
      stackable: false,
      backgroundColor: "rgb(79, 95 , 127)",
      borderColor: "rgb(15, 15 , 15)",
      displaySelf: false,
      groupAction: "Chain Stratagem",
      job: "sch",
	  type: "Crit"},
	{ name: "Battle Voice",
	  shortName: "BV",
	  description: "Direct hit rate is increased.",
	  value: 0.15,
	  duration: 20,
	  recast: 180,
      openerTime: 5,
      stackable: false,
      backgroundColor: "rgb(115, 137, 144)",
      borderColor: "rgb(77, 32, 32)",
      displaySelf: false,
      groupAction: "Battle Voice",
      job: "brd",
	  type: "DH"},
	{ name: "Critical Up",
	  shortName: "CU",
	  description: "Critical hit rate is increased.",
	  value: 0.02,
	  duration: 30,
	  usePattern: [30, 30, 20],
      openerTime: 4,
      stackable: false,
      backgroundColor: "rgb(166, 172 , 141)",
      borderColor: "rgb(83, 86 , 71)",
      displaySelf: false,
      groupAction: "The Wanderer's Minuet",
      job: "brd",
	  type: "Crit"},
	{ name: "Left Eye",
	  shortName: "DS",
	  description: "Damage dealt is increased.",
	  value: 1.05,
	  duration: 20,
	  recast: 120,
      openerTime: 2,
      stackable: true,
      backgroundColor: "rgb(183, 67, 44)",
      borderColor: "rgb(91, 34, 22)",
      displaySelf: false,
      groupAction: "Dragon Sight",
      job: "drg",
	  type: "Damage"},
	{ name: "Brotherhood",
	  shortName: "BH",
	  description: "Physical damage dealt is increased.",
	  value: 1.05,
	  duration: 15,
	  recast: 90,
      openerTime: 11,
      stackable: false,
      backgroundColor: "rgb(147, 28, 7)",
      borderColor: "rgb(49, 40, 33)",
      displaySelf: false,
      groupAction: "Brotherhood",
      job: "mnk",
	  type: "Damage"},
	{ name: "Embolden",
	  shortName: "EM",
	  description: "Physical damage dealt is increased.",
	  value: 1.0,
	  stackValue: 0.02,
	  duration: 20,
	  stackDuration: 4,
      maxStacks: 5,
	  recast: 120,
      openerTime: 12,
      stackable: false,
      backgroundColor: "rgb(214, 80, 25)",
      borderColor: "rgb(56, 47, 43)",
      displaySelf: false,
      groupAction: "Embolden",
      job: "rdm",
	  type: "Damage"},
	{ name: "Devotion",
	  shortName: "DV",
	  description: "Damage dealt and healing magic potency are increased, while damage taken is reduced.",
	  value: 1.02,
	  duration: 15,
	  recast: 120,
      openerTime: 5,
      stackable: false,
      backgroundColor: "rgb(177, 153 , 84)",
      borderColor: "rgb(89, 77 , 42)",
      displaySelf: false,
      groupAction: "Devotion",
      job: "smn",
	  type: "Damage"},
	{ name: "The Balance",
	  shortName: "TB",
	  description: "Damage dealt is increased.",
	  value: 1.1,
	  enhancedValue: 1.15,
	  expandedValue: 1.05,
	  duration: 30,
      openerTime: 2,
      stackable: false,
      backgroundColor: "rgb(215, 140 , 95)",
      borderColor: "rgb(108, 70 , 48)",
      displaySelf: false,
      groupAction: "Draw",
      job: "ast",
	  type: "Damage"},
	{ name: "The Spear",
	  shortName: "TS",
	  description: "Critical hit rate is increased.",
	  value: 0.1,
	  enhancedValue: 0.15,
	  expandedValue: 0.05,
	  duration: 30,
      openerTime: 2,
      stackable: false,
      backgroundColor: "rgb(124, 136 , 194)",
      borderColor: "rgb(62, 68 , 97)",
      displaySelf: false,
      groupAction: "Draw",
      job: "ast",
	  type: "Crit"},
	{ name: "The Arrow",
	  shortName: "TA",
	  description: "Weaponskill cast time and recast time, spell cast time and recast time, and auto-attack delay are reduced.",
	  value: 10,
	  enhancedValue: 15,
	  expandedValue: 5,
	  duration: 30,
      openerTime: 2,
      stackable: false,
      backgroundColor: "rgb(117, 145 , 174)",
      borderColor: "rgb(59, 73 , 87)",
      displaySelf: false,
      groupAction: "Draw",
      job: "ast",
	  type: "Speed"},
	{ name: "Foe Requiem",
	  shortName: "FR",
	  description: "Damage taken is increased.",
	  value: 1.03,
	  duration: 32,
	  altDuration: 23,
	  usePattern: [60, 120],
      openerTime: 0,
      stackable: false,
      backgroundColor: "rgb(97, 64 , 89)",
      borderColor: "rgb(49, 32 , 45)",
      displaySelf: false,
      groupAction: "Foe Requiem",
      job: "brd",
	  type: "Damage"},
	{ name: "Radiant Shield",
	  shortName: "RS",
	  description: "Physical damage taken is increased.",
	  value: 1.02,
	  duration: 22,
	  recast: 60,
      openerTime: -5,
      stackable: false,
      backgroundColor: "rgb(160, 32, 32)",
      borderColor: "rgb(160, 160, 160)",
      displaySelf: false,
      groupAction: "Radiant Shield",
      job: "smn",
	  type: "Damage"}
];

var groupActions = [
	{ name: "Disembowel",
	  shortName: "DE",
	  id: 0,
	  description: "Delivers an attack with a potency of 100.<br/>Combo Action: Impulse Drive<br/>Combo Potency: 240<br/>Combo Bonus: Reduces target's piercing resistance by 5%<br/>Duration: 30s",
	  recast: 2.5,
	  usePattern: [27],
      openerTime: 6.5,
	  effects: ["Piercing Resistance Down"],
      job: "drg"},
	{ name: "Battle Litany",
	  shortName: "BL",
	  id: 1,
	  description: "Increases critical hit rate of self and nearby party members by 15%.<br/>Duration: 20s",
	  recast: 180,
      openerTime: 4,
	  effects: ["Battle Litany"],
      job: "drg"},
	{ name: "Trick Attack",
	  shortName: "TA",
	  id: 2,
	  description: "Delivers an attack with a potency of 240.<br/>400 when executed from a target's rear.<br/>Rear Bonus: Increases target's damage taken by 10%<br/>Duration: 10s",
	  recast: 60,
      openerTime: 11,
	  effects: ["Trick Attack"],
      job: "nin"},
	{ name: "Hypercharge",
	  shortName: "HC",
	  id: 3,
	  description: "Overcharges your autoturret, increasing its normal attack potency.<br/>Duration: 20s<br/>Autoturret Hypercharge Effect: Increases target's damage taken by 5%<br/>Duration: 10s",
	  recast: 120,
      openerTime: 2,
	  effects: ["Hypercharge"],
      job: "mch"},
	{ name: "Fey Wind",
	  shortName: "FW",
	  id: 4,
	  description: "Reduces weaponskill cast time and recast time, spell cast time and recast time, and auto-attack delay of self and nearby party members by 3%.<br/>Duration: 30s",
	  recast: 60,
      openerTime: -5,
	  effects: ["Fey Wind"],
      job: "sch"},
	{ name: "Chain Stratagem",
	  shortName: "CS",
	  id: 5,
	  description: "Increases rate at which target takes critical hits by 15%.<br/>Duration: 15s",
	  recast: 120,
      openerTime: 6,
	  effects: ["Chain Stratagem"],
      job: "sch"},
	{ name: "Battle Voice",
	  shortName: "BV",
	  id: 6,
	  description: "Increases direct hit rate of all party members by 15%.<br/>Duration: 20s",
	  recast: 180,
      openerTime: 5,
	  effects: ["Battle Voice"],
      job: "brd"},
	{ name: "The Wanderer's Minuet",
	  shortName: "WM",
	  id: 7,
	  description: "Deals unaspected damage with a potency of 100.<br/>Additional Effect: Increases critical hit rate of all party members within a radius of 20 yalms by 2%<br/>Duration: 30s<br/>Effect is lost if party members move out of hearing distance.",
	  recast: 90,
	  usePattern: [30, 30, 20],
      openerTime: 4,
	  effects: ["Critical Up"],
      job: "brd"},
	{ name: "Dragon Sight",
	  shortName: "DS",
	  id: 8,
	  description: "Grants Right Eye to self and Left Eye to target party member, increasing your damage dealt by 10% and the target party member's damage dealt by 5%, as long as target remains within 12 yalms.<br/>Duration: 20s",
	  recast: 120,
      openerTime: 2,
	  effects: ["Left Eye"],
      job: "drg"},
	{ name: "Brotherhood",
	  shortName: "BH",
	  id: 9,
	  description: "Grants Brotherhood and Meditative Brotherhood to all nearby party members.<br/>Brotherhood Effect: Increases physical damage dealt by 5%.<br/>Meditative Brotherhood Effect: 30% chance you open a chakra when party members under this effect execute a weaponskill.<br/>Duration: 15s",
	  recast: 90,
      openerTime: 11,
	  effects: ["Brotherhood"],
      job: "mnk"},
	{ name: "Embolden",
	  shortName: "EM",
	  id: 10,
	  description: "Increases own magic damage dealt by 10% and physical damage dealt by nearby party members by 10%. Both effects are reduced by 20% every 4s.<br/>Duration: 20s",
	  recast: 120,
      openerTime: 12,
	  effects: ["Embolden"],
      job: "rdm"},
	{ name: "Devotion",
	  shortName: "DV",
	  id: 11,
	  description: "Increases damage dealt and reduces damage taken by all party members within a 15-yalm radius by 2%. Also increases healing magic potency of all party members by 5%.<br/>Duration: 15s",
	  recast: 120,
      openerTime: 5,
	  effects: ["Devotion"],
      job: "smn"},
	{ name: "Draw",
	  shortName: "DR",
	  id: 12,
	  description: "Draw a card (arcanum) from your divining deck. Execute command again to use the arcanum drawn. Only one arcanum can be drawn at a time.<br/>Duration: 30s",
	  recast: 30,
      openerTime: 2,
	  effects: ["The Balance", "The Spear", "The Arrow"],
      job: "ast"},
	{ name: "Foe Requiem",
	  shortName: "FR",
	  id: 13,
	  description: "Increases damage taken by nearby enemies by 3%. MP is drained while singing. Effect is lost if targets move out of hearing distance, and ends upon reuse.",
	  recast: 2.5,
	  usePattern: [60, 120],
      openerTime: 0,
	  effects: ["Foe Requiem"],
      job: "brd"},
	{ name: "Radiant Shield",
	  shortName: "RS",
	  id: 14,
	  description: "Creates a barrier around self and nearby party members.<br/>Duration: 20s<br/>Barrier Effect: When barrier is struck, increases striker's physical vulnerability by 2%<br/>Duration: 4s",
	  recast: 60,
      openerTime: -5,
	  effects: ["Radiant Shield"],
      job: "smn"}
];

var defaultAnimLock = 0.7;
var scale = 60;

var threeMinRotation = {"wd":109,"str":3207,"dh":1611,"crit":2557,"det":1796,"sks":655,"actions":[{"i":"16","d":"1"},{"i":"24"},{"i":"8"},{"i":"28","d":"1"},{"i":"13","d":"1"},{"i":"4"},{"i":"14","d":"1"},{"i":"12","d":"1"},{"i":"5"},{"i":"17","d":"1"},{"i":"6"},{"i":"18","d":"0"},{"i":"7"},{"i":"22","d":"0"},{"i":"21","d":"0"},{"i":"3"},{"i":"20","d":"0"},{"i":"0"},{"i":"19","d":"0"},{"i":"1"},{"i":"15","d":"0"},{"i":"21","d":"0"},{"i":"2"},{"i":"3"},{"i":"7"},{"i":"8"},{"i":"4"},{"i":"5"},{"i":"6"},{"i":"7"},{"i":"3"},{"i":"18","d":"0"},{"i":"0"},{"i":"22","d":"0"},{"i":"21","d":"0"},{"i":"1"},{"i":"2"},{"i":"3"},{"i":"7"},{"i":"8"},{"i":"4"},{"i":"5"},{"i":"6"},{"i":"7"},{"i":"3"},{"i":"0"},{"i":"18","d":"0"},{"i":"1"},{"i":"15","d":"0"},{"i":"22","d":"0"},{"i":"2"},{"i":"23","d":"0"},{"i":"21","d":"0"},{"i":"3"},{"i":"19","d":"0"},{"i":"7"},{"i":"8"},{"i":"4"},{"i":"23","d":"0"},{"i":"5"},{"i":"12","d":"1"},{"i":"6"},{"i":"21","d":"0"},{"i":"7"},{"i":"3"},{"i":"23","d":"0"},{"i":"0"},{"i":"1"},{"i":"16","d":"1"},{"i":"2"},{"i":"18","d":"0"},{"i":"3"},{"i":"21","d":"0"},{"i":"22","d":"0"},{"i":"7"},{"i":"23","d":"0"},{"i":"8"},{"i":"4"},{"i":"5"},{"i":"6"},{"i":"23","d":"0"},{"i":"7"},{"i":"3"},{"i":"0"},{"i":"28","d":"1"},{"i":"1"},{"i":"15","d":"0"},{"i":"13","d":"1"},{"i":"2"},{"i":"23","d":"0"},{"i":"3"},{"i":"18","d":"0"},{"i":"7"},{"i":"20","d":"0"},{"i":"8"},{"i":"22","d":"0"},{"i":"21","d":"0"},{"i":"4"},{"i":"19","d":"0"},{"i":"5"},{"i":"21","d":"0"},{"i":"6"},{"i":"7"},{"i":"3"},{"i":"0"},{"i":"1"},{"i":"2"},{"i":"3"},{"i":"7"},{"i":"8"},{"i":"18","d":"0"},{"i":"4"},{"i":"21","d":"0"},{"i":"22","d":"0"},{"i":"5"},{"i":"23","d":"0"},{"i":"12","d":"1"},{"i":"6"},{"i":"7"},{"i":"3"},{"i":"0"},{"i":"23","d":"0"},{"i":"1"},{"i":"15","d":"0"},{"i":"2"},{"i":"14","d":"1"},{"i":"3"},{"i":"7"},{"i":"23","d":"0"},{"i":"8"},{"i":"4"},{"i":"5"},{"i":"18","d":"0"},{"i":"6"},{"i":"22","d":"0"},{"i":"21","d":"0"},{"i":"7"},{"i":"19","d":"0"},{"i":"3"},{"i":"21","d":"0"},{"i":"0"},{"i":"1"},{"i":"2"},{"i":"3"},{"i":"7"}]};